#lang racket/base

(provide (except-out (all-defined-out)
                     string-code?))

;; C0 codes are in the range #\u00-#\u1F
(define c0/null #\null)
(define c0/start-of-heading #\u01)
(define c0/start-of-text #\u02)
(define c0/end-of-text #\u03)
(define c0/end-of-transmission #\u04)
(define c0/enquiry #\u05)
(define c0/acknowledge #\u06)
(define c0/bell #\u07)
(define c0/backspace #\backspace)
(define c0/horizontal-tabulation #\tab)
(define c0/line-feed #\linefeed)
(define c0/vertical-tabulation #\vtab)
(define c0/form-feed #\u0C)
(define c0/carriage-return #\return)
(define c0/shift-out #\u0E)
(define c0/shift-in #\u0F)
(define c0/data-link-escape #\u10)
(define c0/device-control-one #\u11)
(define c0/device-control-two #\u12)
(define c0/device-control-three #\u13)
(define c0/device-control-four #\u14)
(define c0/negative-acknowledge #\u15)
(define c0/synchronous-idle #\u16)
(define c0/end-of-transmission-block #\u17)
(define c0/cancel #\u18)
(define c0/end-of-medium #\u19)
(define c0/substitute #\u1A)
(define c0/escape #\u1B)
(define c0/file-separator #\u1C)
(define c0/group-separator #\u1D)
(define c0/record-separator #\u1E)
(define c0/unit-separator #\u1F)

;; ANSI added the following outside the C0 range.
(define c0/delete #\u7F)

;; C1 codes are in the range #\u80-#\u9F
(define c1/padding-character #\u80)
(define c1/high-octal-preset #\u81)
(define c1/break-permitted-here #\u82)
(define c1/no-break-here #\u83)
(define c1/index #\u84)
(define c1/next-line #\u85)
(define c1/start-of-selected-area #\u86)
(define c1/end-of-selected-area #\u87)
(define c1/horizontal-tabulation-set #\u88)
(define c1/horizontal-tabulation-with-justification #\u89)
(define c1/vertical-tabulation-set #\u8A)
(define c1/parial-line-down #\u8B)
(define c1/parial-line-up #\u8C)
(define c1/reverse-line-feed #\u8D)
(define c1/single-shift-2 #\u8E)
(define c1/single-shift-3 #\u8F)
(define c1/device-control-string #\u90)
(define c1/private-use-1 #\u91)
(define c1/private-use-2 #\u92)
(define c1/set-transmission-state #\u93)
(define c1/cancel-character #\u94)
(define c1/message-waiting #\u95)
(define c1/start-of-protected-area #\u96)
(define c1/end-of-protected-area #\u97)
(define c1/start-of-string #\u98)
(define c1/single-graphic-character-introducer #\u99)
(define c1/single-character-introducer #\u9A)
(define c1/control-sequence-introducer #\u9B)
(define c1/string-terminator #\u9C)
(define c1/operating-system-command #\u9D)
(define c1/privacy-message #\u9E)
(define c1/application-program-command #\u9F)

(define (char-c0-code? c)
  (and (char? c)
       (or (char<=? c0/null c c0/unit-separator)
           (char=? c c0/delete))))

(define (char-c1-code? c)
  (and (char? c)
       (char<=? c1/padding-character c c1/application-program-command)))

(define (string-code? s char-in-code?)
  (and (string? s)
       (= (string-length s) 2)
       (char=? (string-ref s 0) c0/escape)
       (char-in-code? (string-ref s 1))))

(define (string-c1-code? s)
  (string-code? s char-c1-code?))


(define (char-fe-code? c)
  (and (char? c)
       (char<=? #\u40 c #\u5F)))


(define (char-fs-code? c)
  (and (char? c)
       (char<=? #\u60 c #\u7F)))


(define (char-fp-code? c)
  (and (char? c)
       (char<=? #\u30 c #\u3F)))


(define (char-nf-code? c)
  (and (char? c)
       (char<=? #\u20 c #\u2F)))

(define c0-symbol/null #\U2400)
(define c0-symbol/start-of-heading #\U2401)
(define c0-symbol/start-of-text #\U2402)
(define c0-symbol/end-of-text #\U2403)
(define c0-symbol/end-of-transmission #\U2404)
(define c0-symbol/enquiry #\U2405)
(define c0-symbol/acknowledge #\U2406)
(define c0-symbol/bell #\U2407)
(define c0-symbol/backspace #\U2408)
(define c0-symbol/horizontal-tabulation #\U2409)
(define c0-symbol/line-feed #\U240A)
(define c0-symbol/vertical-tabulation #\U240B)
(define c0-symbol/form-feed #\U240C)
(define c0-symbol/carriage-return #\U240D)
(define c0-symbol/shift-out #\U240E)
(define c0-symbol/shift-in #\U240F)
(define c0-symbol/data-link-escape #\U2410)
(define c0-symbol/device-control-one #\U2411)
(define c0-symbol/device-control-two #\U2412)
(define c0-symbol/device-control-three #\U2413)
(define c0-symbol/device-control-four #\U2414)
(define c0-symbol/negative-acknowledge #\U2415)
(define c0-symbol/synchronous-idle #\U2416)
(define c0-symbol/end-of-transmission-block #\U2417)
(define c0-symbol/cancel #\U2418)
(define c0-symbol/end-of-medium #\U2419)
(define c0-symbol/substitute #\U241A)
(define c0-symbol/escape #\U241B)
(define c0-symbol/file-separator #\U241C)
(define c0-symbol/group-separator #\U241D)
(define c0-symbol/record-separator #\U241E)
(define c0-symbol/unit-separator #\U241F)
(define c0-symbol/space #\U2420)
(define c0-symbol/delete #\U2421)
(define c0-symbol/blank #\U2422)
(define c0-symbol/open-box #\U2423)
(define c0-symbol/newline #\U2424)
(define c0-symbol/delete-form-two #\U2425)
(define c0-symbol/substitute-form-two #\U2426)

(define (char-c0-symbol? c)
  (and (char? c)
       (char<=? c0-symbol/null c c0-symbol/substitute-form-two)))

(define (c0-symbol c)
  (if (char-c0-code? c)
      (integer->char (+ (char->integer c) #x2400))
      #f))
